Repository Manie-K/Distributed-World-Evolution, pull requests merged in 2025-09, with the labels that each got.

#53 cleaning up shared projects mess
  Server/Server.Core/Entities/EntityState.cs
  Server/Server.Core/Entities/WorldEntity.cs
  Server/Server.Core/Exceptions/BehaviourImplementationNotFoundException.cs
  Server/Server.Core/Exceptions/NullLobbyException.cs
  Server/Server.Core/Helpers/InterfaceHelpers.cs
  Server/Server.Core/Lobby/Lobby.cs
  Server/Server.Core/Lobby/LobbyController.cs
  Server/Server.Core/Lobby/LobbyManager.cs
  Server/Server.Core/Modules/BasicAttackBehaviour.cs
  Server/Server.Core/Modules/BasicMoveBehaviour.cs
  Server/Server.Core/Modules/BehaviourFactory.cs
  Server/Server.Core/Modules/BehaviourInMemoryDB.cs
  Server/Server.Core/Modules/BehaviourService.cs
  Server/Server.Core/Modules/IAttackBehaviour.cs
  Server/Server.Core/Modules/IBehaviour.cs
  Server/Server.Core/Modules/IBehaviourService.cs
  Server/Server.Core/Modules/IModuleService.cs
  Server/Server.Core/Modules/IMoveBehaviour.cs
  Server/Server.Core/Modules/Module.cs
  Server/Server.Core/Modules/ModuleService.cs
  Server/Server.Core/OnMessageFromClientEventArgs.cs
  Server/Server.Core/Server.Core.csproj
  Server/Server.Core/Server.cs
  Server/Server.Shared/Modules/BehviourDTO.cs
  Server/Server.Shared/Modules/CreateModuleDTO.cs
  Server/Server.UI/Server.UI.csproj
  Server/Server.UI/ViewModels/BaseTabViewModel.cs
  Server/Server.UI/ViewModels/MainViewModel.cs
  Server/Server.sln
  Server/TemporaryManualServerTests/TemporaryManualServerTests.csproj
  Shared/SharedLibrary/LobbyDTO/LobbyDTO.cs
  Shared/SharedLibrary/LobbyDTO/LobbyService.cs
  Shared/SharedLibrary/Logging/LogLevelEnum.cs
  Shared/SharedLibrary/Logging/OnLogEventArgs.cs
  Shared/SharedLibrary/Messages/CreateLobbyMessage.cs
  Shared/SharedLibrary/Messages/DisjoinLobbyMessage.cs
  Shared/SharedLibrary/Messages/EntityStateMessage.cs
  Shared/SharedLibrary/Messages/InfoMessage.cs
  Shared/SharedLibrary/Messages/JoinLobbyMessage.cs
  Shared/SharedLibrary/Messages/LogMessage.cs
  Shared/SharedLibrary/Messages/MessageBase.cs
  Shared/SharedLibrary/Messages/MessageManager.cs
  Shared/SharedLibrary/Messages/MessageTypeEnum.cs
  Shared/SharedLibrary/Messages/RoleMessage.cs
  Shared/SharedLibrary/Messages/UserStateMessage.cs
  Shared/SharedLibrary/Messages/WorldStateMessage.cs
  Shared/SharedLibrary/ModuleDTO/BehviourDTO.cs
  Shared/SharedLibrary/ModuleDTO/CreateModuleDTO.cs
  Shared/SharedLibrary/ModuleDTO/ModuleDTO.cs
Labels: bug

#55 Changed fields in ModuleDTO.
  Server/Server.Core/Entities/EntityState.cs
  Server/Server.Core/Entities/WorldEntity.cs
  Server/Server.Core/Lobby/Lobby.cs
  Server/Server.Core/Lobby/LobbyController.cs
  Server/Server.Core/Modules/IModuleService.cs
  Server/Server.Core/Modules/ModuleService.cs
  Server/Server.Tests/Class1.cs
  Server/Server.UI/ViewModels/MainViewModel.cs
  Shared/SharedLibrary/DTOs/EntitiesDTO/EntityStateDTO.cs
  Shared/SharedLibrary/DTOs/EntitiesDTO/WorldEntityDTO.cs
  Shared/SharedLibrary/DTOs/LobbyDTO/LobbyDTO.cs
  Shared/SharedLibrary/DTOs/ModuleDTO/BehviourDTO.cs
  Shared/SharedLibrary/DTOs/ModuleDTO/CreateModuleDTO.cs
  Shared/SharedLibrary/DTOs/ModuleDTO/ModuleDTO.cs
  Shared/SharedLibrary/Messages/EntityStateMessage.cs
  Shared/SharedLibrary/Messages/WorldStateMessage.cs
  Shared/SharedLibrary/ModuleDTO/BehviourDTO.cs
  Shared/SharedLibrary/ModuleDTO/CreateModuleDTO.cs
  Shared/SharedLibrary/ModuleDTO/ModuleDTO.cs
  Shared/SharedLibrary/Services/LobbyService.cs
Labels: enhancement

#57 added messages for getting lobbies and modules
  Server/Server.Core/Server.cs
  Shared/SharedLibrary/Messages/GetMessage.cs
  Shared/SharedLibrary/Messages/GetMessageTypeEnum.cs
  Shared/SharedLibrary/Messages/LobbyMessages/EntityStateMessage.cs
  Shared/SharedLibrary/Messages/LobbyMessages/LobbiesMessage.cs
  Shared/SharedLibrary/Messages/LobbyMessages/UserStateMessage.cs
  Shared/SharedLibrary/Messages/LobbyMessages/WorldStateMessage.cs
  Shared/SharedLibrary/Messages/MessageTypeEnum.cs
  Shared/SharedLibrary/Messages/ModuleMessages/CreateModuleMessage.cs
  Shared/SharedLibrary/Messages/ModuleMessages/ModulesMessage.cs
  Shared/SharedLibrary/Messages/UserMessages/CreateLobbyMessage.cs
  Shared/SharedLibrary/Messages/UserMessages/DisjoinLobbyMessage.cs
  Shared/SharedLibrary/Messages/UserMessages/JoinLobbyMessage.cs
  Shared/SharedLibrary/Messages/UserMessages/RoleEnum.cs
  Shared/SharedLibrary/Messages/UserMessages/RoleMessage.cs
Labels: enhancement

#63 info message type and changes in UI console
  Server/Server.Core/Lobby/Lobby.cs
  Server/Server.Core/Lobby/LobbyController.cs
  Server/Server.Core/Program.cs
  Server/Server.Core/Server.Core.csproj
  Server/Server.Core/Server.cs
  Server/Server.UI/ViewModels/LobbyViewModel.cs
  Server/Server.UI/ViewModels/MainViewModel.cs
  Shared/SharedLibrary/DTOs/LobbyDTO/LobbyDTO.cs
  Shared/SharedLibrary/Messages/ErrorMessage.cs
  Shared/SharedLibrary/Messages/GetMessages/GetMessage.cs
  Shared/SharedLibrary/Messages/GetMessages/GetMessageTypeEnum.cs
  Shared/SharedLibrary/Messages/InfoMessages/InfoMessage.cs
  Shared/SharedLibrary/Messages/InfoMessages/InfoMessageTypeEnum.cs
  Shared/SharedLibrary/Messages/LobbyMessages/CreateLobbyMessage.cs
  Shared/SharedLibrary/Messages/LobbyMessages/DisjoinLobbyMessage.cs
  Shared/SharedLibrary/Messages/LobbyMessages/JoinLobbyMessage.cs
  Shared/SharedLibrary/Messages/LobbyMessages/LobbyListMessage.cs
  Shared/SharedLibrary/Messages/LobbyMessages/LobbyMessage.cs
  Shared/SharedLibrary/Messages/LogMessage.cs
  Shared/SharedLibrary/Messages/MessageManager.cs
  Shared/SharedLibrary/Messages/MessageTypeEnum.cs
  Shared/SharedLibrary/Messages/ModuleMessages/CreateModuleMessage.cs
  Shared/SharedLibrary/Messages/ModuleMessages/ModuleListMessage.cs
  Shared/SharedLibrary/Messages/RoleMessages/RoleEnum.cs
  Shared/SharedLibrary/Messages/RoleMessages/RoleMessage.cs
  Shared/SharedLibrary/Messages/SimulationMessages/EntityStateMessage.cs
  Shared/SharedLibrary/Messages/SimulationMessages/UserStateMessage.cs
  Shared/SharedLibrary/Messages/SimulationMessages/WorldStateMessage.cs
  Shared/SharedLibrary/Messages/UserMessages/RoleEnum.cs
  Shared/SharedLibrary/Services/LobbyService.cs
Labels: bug, enhancement
